modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
issueTrackerURL="https://github.com/mpbb/ironbows/issues" #optional
[[mods]]
modId="ironbows"
version="1.19-1.0"
displayName="Iron Bows"
displayURL="https://github.com/mpbb/ironbows"
logoFile="icon.png"
credits="Popcornman200, lucam, Mr.Bananas"
authors="Popcornman200"
description='''
This mod adds new and superior bows. Iron, Golden, Diamond, Emerald and Netherite. Each bow has differences in durability and damage.
'''
